import {
  type AppState,
  type CandidateProfile,
  type FeedbackEvent,
  type JobSource,
  type NormalizedJob,
  type PipelineRun,
  type RawJobPosting,
  defaultPreferences,
} from "@/lib/types";

const hoursAgo = (hours: number) => new Date(Date.now() - hours * 60 * 60 * 1000);

export function buildDemoState(): AppState {
  const now = new Date();

  const candidateProfile: CandidateProfile = {
    id: "candidate_demo",
    resumeFilename: "nick_resume.pdf",
    sourceFileType: "application/pdf",
    rawResumeText:
      "Systems engineer with 4 years in EV integration, CAN diagnostics, validation, Python automation, J1939, and charger systems.",
    skills: ["CAN", "J1939", "Validation", "EV systems", "Integration", "Diagnostics"],
    roles: ["Systems Engineer", "Integration Engineer"],
    industries: ["Automotive", "EV"],
    tools: ["Python", "C++", "Vector CANalyzer"],
    education: ["MS Electrical Engineering"],
    domains: ["Vehicle systems", "Charging", "Embedded diagnostics"],
    yearsExperience: 4,
    seniorityEstimate: "mid",
    parseConfidence: 88,
    createdAt: now,
    updatedAt: now,
  };

  const sources: JobSource[] = [
    {
      id: "source_greenhouse_demo",
      name: "Greenhouse Demo Feed",
      type: "static",
      baseUrl: "https://boards-api.greenhouse.io/v1/boards/demo/jobs",
      enabled: true,
      fetchStrategy: "seeded-static",
      selectorConfig: {
        jobs: [
          {
            sourceJobId: "gh-101",
            url: "https://careers.example.com/jobs/gh-101",
            title: "Systems Integration Engineer",
            company: "HelioDrive",
            location: "Palo Alto, CA",
            description:
              "Build and validate EV subsystems. Strong CAN, integration, Python test tooling, and charger knowledge required. Sponsorship available.",
            postedAtRaw: hoursAgo(18).toISOString(),
          },
          {
            sourceJobId: "gh-102",
            url: "https://careers.example.com/jobs/gh-102",
            title: "Vehicle Validation Engineer",
            company: "Axiom Motion",
            location: "Remote - US",
            description:
              "Own EV validation plans, HIL coordination, CAN log review, and integration issue triage. Mid-level preferred. Sponsorship unclear.",
            postedAtRaw: hoursAgo(10).toISOString(),
          },
        ],
      },
      lastFetchedAt: hoursAgo(2),
      lastFetchStatus: "success",
      lastFetchMessage: "Loaded seeded greenhouse-style jobs.",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "source_lever_demo",
      name: "Lever Demo Feed",
      type: "static",
      baseUrl: "https://api.lever.co/v0/postings/demo?mode=json",
      enabled: true,
      fetchStrategy: "seeded-static",
      selectorConfig: {
        jobs: [
          {
            sourceJobId: "lv-201",
            url: "https://jobs.example.com/jobs/lv-201",
            title: "EVSE Systems Engineer",
            company: "Charge Forge",
            location: "Charlotte, NC",
            description:
              "Lead charging system integration, EVSE interoperability, and field diagnostics. CAN helpful. No sponsorship offered.",
            postedAtRaw: hoursAgo(30).toISOString(),
          },
          {
            sourceJobId: "lv-202",
            url: "https://jobs.example.com/jobs/lv-202",
            title: "Robotics Platform Engineer",
            company: "Forge Robotics",
            location: "San Jose, CA",
            description:
              "Cross-functional integration role spanning sensors, system bring-up, and automation. Python, C++, and validation workflows required.",
            postedAtRaw: hoursAgo(6).toISOString(),
          },
        ],
      },
      lastFetchedAt: hoursAgo(2),
      lastFetchStatus: "success",
      lastFetchMessage: "Loaded seeded lever-style jobs.",
      createdAt: now,
      updatedAt: now,
    },
  ];

  const rawJobs: RawJobPosting[] = [
    {
      id: "raw_1",
      sourceId: "source_greenhouse_demo",
      sourceJobId: "gh-101",
      url: "https://careers.example.com/jobs/gh-101",
      rawTitle: "Systems Integration Engineer",
      rawCompany: "HelioDrive",
      rawLocation: "Palo Alto, CA",
      rawDescription:
        "Build and validate EV subsystems. Strong CAN, integration, Python test tooling, and charger knowledge required. Sponsorship available.",
      postedAtRaw: hoursAgo(18).toISOString(),
      fetchedAt: hoursAgo(2),
      contentHash: "demo_hash_1",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "raw_2",
      sourceId: "source_greenhouse_demo",
      sourceJobId: "gh-102",
      url: "https://careers.example.com/jobs/gh-102",
      rawTitle: "Vehicle Validation Engineer",
      rawCompany: "Axiom Motion",
      rawLocation: "Remote - US",
      rawDescription:
        "Own EV validation plans, HIL coordination, CAN log review, and integration issue triage. Mid-level preferred. Sponsorship unclear.",
      postedAtRaw: hoursAgo(10).toISOString(),
      fetchedAt: hoursAgo(2),
      contentHash: "demo_hash_2",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "raw_3",
      sourceId: "source_lever_demo",
      sourceJobId: "lv-201",
      url: "https://jobs.example.com/jobs/lv-201",
      rawTitle: "EVSE Systems Engineer",
      rawCompany: "Charge Forge",
      rawLocation: "Charlotte, NC",
      rawDescription:
        "Lead charging system integration, EVSE interoperability, and field diagnostics. CAN helpful. No sponsorship offered.",
      postedAtRaw: hoursAgo(30).toISOString(),
      fetchedAt: hoursAgo(2),
      contentHash: "demo_hash_3",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "raw_4",
      sourceId: "source_lever_demo",
      sourceJobId: "lv-202",
      url: "https://jobs.example.com/jobs/lv-202",
      rawTitle: "Robotics Platform Engineer",
      rawCompany: "Forge Robotics",
      rawLocation: "San Jose, CA",
      rawDescription:
        "Cross-functional integration role spanning sensors, system bring-up, and automation. Python, C++, and validation workflows required.",
      postedAtRaw: hoursAgo(6).toISOString(),
      fetchedAt: hoursAgo(2),
      contentHash: "demo_hash_4",
      createdAt: now,
      updatedAt: now,
    },
  ];

  const normalizedJobs: NormalizedJob[] = [
    {
      id: "job_1",
      rawJobPostingId: "raw_1",
      titleNormalized: "Systems Integration Engineer",
      company: "HelioDrive",
      locationNormalized: "Palo Alto, CA",
      remoteType: "onsite",
      skillsRequired: ["CAN", "Integration", "Python", "EV Systems"],
      skillsPreferred: ["Validation", "Charging"],
      industry: "EV",
      seniority: "mid",
      sponsorshipStatus: "yes",
      salaryMin: 110000,
      salaryMax: 145000,
      postedAt: hoursAgo(18),
      parseConfidence: 92,
      status: "active",
      confidenceFlags: [],
      hiddenMatch: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "job_2",
      rawJobPostingId: "raw_2",
      titleNormalized: "Validation Engineer",
      company: "Axiom Motion",
      locationNormalized: "Remote - US",
      remoteType: "remote",
      skillsRequired: ["Validation", "CAN", "Integration"],
      skillsPreferred: ["HIL", "Triage"],
      industry: "Automotive",
      seniority: "mid",
      sponsorshipStatus: "unknown",
      salaryMin: 98000,
      salaryMax: 125000,
      postedAt: hoursAgo(10),
      parseConfidence: 80,
      status: "active",
      confidenceFlags: ["sponsorship_unknown"],
      hiddenMatch: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "job_3",
      rawJobPostingId: "raw_3",
      titleNormalized: "EVSE Systems Engineer",
      company: "Charge Forge",
      locationNormalized: "Charlotte, NC",
      remoteType: "hybrid",
      skillsRequired: ["EVSE", "Integration", "Diagnostics"],
      skillsPreferred: ["CAN"],
      industry: "EV",
      seniority: "mid",
      sponsorshipStatus: "no",
      salaryMin: 100000,
      salaryMax: 130000,
      postedAt: hoursAgo(30),
      parseConfidence: 86,
      status: "active",
      confidenceFlags: [],
      hiddenMatch: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "job_4",
      rawJobPostingId: "raw_4",
      titleNormalized: "Platform Integration Engineer",
      company: "Forge Robotics",
      locationNormalized: "San Jose, CA",
      remoteType: "onsite",
      skillsRequired: ["Python", "C++", "Validation"],
      skillsPreferred: ["Robotics", "Systems"],
      industry: "Robotics",
      seniority: "mid",
      sponsorshipStatus: "unknown",
      salaryMin: 115000,
      salaryMax: 150000,
      postedAt: hoursAgo(6),
      parseConfidence: 78,
      status: "active",
      confidenceFlags: ["sponsorship_unknown"],
      hiddenMatch: true,
      createdAt: now,
      updatedAt: now,
    },
  ];

  const feedbackEvents: FeedbackEvent[] = [
    {
      id: "feedback_1",
      normalizedJobId: "job_1",
      feedbackType: "up",
      createdAt: hoursAgo(1),
    },
  ];

  const pipelineRuns: PipelineRun[] = [
    {
      id: "run_1",
      trigger: "manual",
      status: "success",
      startedAt: hoursAgo(2),
      finishedAt: hoursAgo(2),
      jobsFetched: rawJobs.length,
      jobsParsed: normalizedJobs.length,
      jobsScored: normalizedJobs.length,
      message: "Demo pipeline hydrated seeded curated sources.",
      createdAt: now,
      updatedAt: now,
    },
  ];

  return {
    candidateProfile,
    preferences: {
      id: "preferences_demo",
      ...defaultPreferences,
      createdAt: now,
      updatedAt: now,
    },
    sources,
    rawJobs,
    normalizedJobs,
    matchResults: [],
    feedbackEvents,
    pipelineRuns,
  };
}
